# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.6
python: 3.6

# Install the codecov pip dependency
install:
  - pip install -Ur requirements.txt

# Run the unit test
script:
  - pytest --cov=lsmhun 

# Push the results back to codecov
after_success:
- codecov
